#!/usr/bin/env sh
set -eu

export PYTHONPATH="${SNAP}/opt/koplyx:${PYTHONPATH:-}"
export XDG_DATA_DIRS="${SNAP}/usr/share:${SNAP}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
# L'extension GNOME initialise les chargeurs GdkPixbuf. Ne pas utiliser
# SNAPCRAFT_ARCH_TRIPLET ici : cette variable n'existe qu'au build.

exec python3 "${SNAP}/opt/koplyx/koplyx/main.py" "$@"
