#!/usr/bin/env sh
set -eu

export PYTHONPATH="${SNAP}/opt/koplyx:${PYTHONPATH:-}"
export XDG_DATA_DIRS="${SNAP}/usr/share:${SNAP}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export GDK_PIXBUF_MODULE_FILE="${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders.cache"

exec "${SNAP}/usr/bin/python3" "${SNAP}/opt/koplyx/koplyx/main.py" "$@"
